[package]
build = "../../scripts/native/build.rs"
name = "pty-runtime-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
pty-runtime-domain = { path = "../domain" }
pty-runtime-application = { path = "../application" }
libc = "=0.2.189"
futures-channel = "0.3"
chacha20poly1305 = "=0.10.1"
getrandom = "=0.2.16"
zeroize = "=1.9.0"

[lints]
workspace = true

[features]
ghostty = []
