#!/usr/bin/env python3
"""Collect verbatim notices from pinned Cargo and native source packages."""
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]


def licenses(root):
    return sorted(p for p in root.rglob('*') if p.is_file()
                  and not {'.git', 'target', '.zig-cache', 'zig-out'} & set(p.relative_to(root).parts)
                  and p.name.lower().split('.')[0] in {'license', 'licence', 'copying', 'notice',
                                                      'license-mit', 'license-apache', 'license-unicode',
                                                      'license-apache-2', 'license-bsd'})


def main():
    sections = ['# Third-party source notices\n\nGenerated by `python3 scripts/release/notices.py` from the locked dependencies.\n'
                'This inventory includes optional, development and target-specific Cargo dependencies, plus a conservative superset of native build dependencies.\n'
                'It does not grant a license to this private repository or unlicensed dependencies.\n']
    inventory = []
    packages = {}
    for manifest in ['Cargo.toml', 'helpers/guardian/Cargo.toml']:
        metadata = json.loads(subprocess.check_output([
            'cargo', 'metadata', '--locked', '--all-features', '--format-version', '1',
            '--manifest-path', manifest], cwd=ROOT))
        for package in metadata['packages']:
            if package['source']:
                packages[package['id']] = package
    sources = []
    for package in sorted(packages.values(), key=lambda p: (p['name'], p['version'])):
        sources.append((package['name'] + ' ' + package['version'],
                        Path(package['manifest_path']).parent,
                        package['source'], package['license'] or 'No SPDX license declared'))
    pin = json.loads((ROOT / 'experiments/dependencies.json').read_text())['ghostty']
    native = ROOT / 'work/experiment-cache' / ('ghostty-' + pin['revision'])
    sources.append(('Ghostty ' + pin['revision'], native, pin['url'], 'See verbatim source notices'))
    for label, root, source, declared in sources:
        if not root.is_dir():
            raise SystemExit('Missing pinned source: ' + label)
        found = licenses(root)
        sections.append('\n## ' + label + '\n\nSource: `' + source + '`\n\nDeclared license: ' + declared + '\n')
        if not found:
            sections.append('\nNo license/notice file was found in this source package. Distribution permission is not established by this inventory.\n')
        for path in found:
            raw = path.read_bytes()
            name = str(path.relative_to(root))
            inventory.append(dict(package=label, path=name, sha256=hashlib.sha256(raw).hexdigest()))
            sections.append('\n### ' + name + '\n\n````text\n' + raw.decode('utf-8') + '\n````\n')
    (ROOT / 'THIRD_PARTY_NOTICES.md').write_text(''.join(sections))
    (ROOT / 'docs/third-party-notice-inventory.json').write_text(json.dumps(inventory, indent=2) + '\n')
    print(f'Collected {len(inventory)} verbatim license/notice files from {len(sources)} source packages.')


if __name__ == '__main__':
    main()
