pub mod allocator;
pub mod config;
pub mod fixture;
pub mod observe;
pub mod payload;
pub mod population;
pub mod report;
pub mod run;
pub mod wire;
pub type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;
pub const DEADLINE: std::time::Duration = std::time::Duration::from_secs(30);
pub mod cancel;
pub mod phase;
pub mod producer;
pub mod resize;
pub mod resources;
pub mod sink;
